# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-25 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('cover', models.TextField()),
                ('position', models.CharField(choices=[('developer', 'Software Developer'), ('designer', 'Graphic Designer'), ('devops', 'Devops')], max_length=8)),
                ('status', models.CharField(choices=[('new', 'New'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='new', max_length=8)),
            ],
        ),
    ]
