# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-25 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='position',
            field=models.CharField(choices=[('developer', 'Software Developer'), ('designer', 'Graphic Designer'), ('devops', 'Devops')], max_length=16),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='new', max_length=16),
        ),
    ]
